name: Review Checklist PR Comment

on:
  pull_request:
    types:
      - opened

jobs:
  auto-comment:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: PR Comment
        run: gh pr comment $PRNUM --body-file .github/workflows/review_checklist.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
